-------------------------------------ACTIONS
STRINGS.ACTIONS.HAUNT = "Haunt"
-------------------------------------
STRINGS.NAMES.ROCK_MOON = "Boulder"
STRINGS.NAMES.ROCK_MOON_SHELL = "Suspicious Boulder"
STRINGS.NAMES.MOONROCKNUGGET = "Moon Rock"

STRINGS.NAMES.ROCK_PETRIFIED_TREE = "Petrified Tree"

STRINGS.NAMES.TWIGGYTREES_REGROWTH = "Twiggy Trees"
STRINGS.NAMES.TWIGGYTREE = "Twiggy Tree"
STRINGS.NAMES.TWIGGY_NUT = "Twiggy Tree Cone"
STRINGS.NAMES.TWIGGY_NUT_SAPLING = "Twiggy Sapling"

STRINGS.NAMES.GRASSGEKKO = "Grass Gekko"
STRINGS.NAMES.GRASSGEKKOS = "Grass Gekko Morphing"

STRINGS.NAMES.DUG_BERRYBUSH_JUICY = "Juicy Berry Bush"
STRINGS.NAMES.BERRYBUSH_JUICY = "Juicy Berry Bush"