STRINGS.NAMES.ROCK_MOON = "Boulder"
STRINGS.NAMES.ROCK_MOON_SHELL = "Suspicious Boulder"

STRINGS.NAMES.ROCK_PETRIFIED_TREE = "Petrified Tree"

STRINGS.NAMES.TWIGGYTREES_REGROWTH = "Twiggy Trees"
STRINGS.NAMES.TWIGGYTREE = "Twiggy Tree"