TUNING.HAUNT_COOLDOWN_TINY = 1
TUNING.HAUNT_COOLDOWN_SMALL = 3
TUNING.HAUNT_COOLDOWN_MEDIUM = 5
TUNING.HAUNT_COOLDOWN_LARGE = 7
TUNING.HAUNT_COOLDOWN_HUGE = 10

TUNING.HAUNT_CHANCE_ALWAYS = 1
TUNING.HAUNT_CHANCE_OFTEN = .75
TUNING.HAUNT_CHANCE_HALF = .5
TUNING.HAUNT_CHANCE_OCCASIONAL = .25
TUNING.HAUNT_CHANCE_RARE = .1
TUNING.HAUNT_CHANCE_VERYRARE = .005
TUNING.HAUNT_CHANCE_SUPERRARE = .001

TUNING.HAUNT_TINY = 1
TUNING.HAUNT_SMALL = 3
TUNING.HAUNT_MEDIUM = 5
TUNING.HAUNT_MEDLARGE = 7
TUNING.HAUNT_LARGE = 10
TUNING.HAUNT_HUGE = 15
TUNING.HAUNT_INSTANT_REZ = 9999

TUNING.LAUNCH_SPEED_SMALL = 3
TUNING.LAUNCH_SPEED_MEDIUM = 5
TUNING.LAUNCH_SPEED_LARGE = 7

TUNING.HAUNT_PANIC_TIME_SMALL = 3
TUNING.HAUNT_PANIC_TIME_MEDIUM = 5
TUNING.HAUNT_PANIC_TIME_LARGE = 7

TUNING.PETRIFIED_TREE_SMALL = 2
TUNING.PETRIFIED_TREE_NORMAL = 3
TUNING.PETRIFIED_TREE_TALL = 4
TUNING.PETRIFIED_TREE_OLD = 1
